import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion'; // eslint-disable-line no-unused-vars

// Reusable Content Component
export function TermsContent() {
    return (
        <article className="prose prose-gray max-w-none space-y-8">
            <section>
                <h2 className="text-xl font-bold text-gray-900 mb-4">Electronic Record</h2>
                <p className="text-gray-600 leading-relaxed">
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-gray-900 mb-4">Publication</h2>
                <p className="text-gray-600 leading-relaxed">
                    This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name ('Website'), including the related mobile site and mobile application (https://zivahmedicalhub.com/) (hereinafter referred to as 'Platform').
                </p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-gray-900 mb-4">Platform Ownership</h2>
                <p className="text-gray-600 leading-relaxed">
                    The Platform is owned by a company incorporated under the Companies Act, 1956 with its registered office at Revenue Ward, 13, Khaja Nagar, Srinivas Nagar, Anantapur, Andhra Pradesh 515001 (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
                </p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-gray-900 mb-4">Terms of Use</h2>
                <p className="text-gray-600 leading-relaxed mb-4">
                    Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") including the applicable policies which are incorporated herein by way of reference.
                </p>
                <p className="text-gray-600 leading-relaxed mb-4">
                    By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions constitute Your binding obligations.
                </p>
                <p className="text-gray-600 leading-relaxed mb-4">
                    These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use.
                </p>
                <p className="text-gray-600 leading-relaxed">
                    Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and conditions.
                </p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-gray-900 mb-4">User Obligations</h2>
                <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
                    <ul className="space-y-3 list-disc pl-5 text-sm text-gray-600">
                        <li>To access and use the Services, you agree to provide true, accurate and complete information during registration.</li>
                        <li>Neither we nor any third parties provide any warranty as to accuracy, timeliness, performance, completeness or suitability of the information.</li>
                        <li>Your use of the Platform is entirely at your own risk.</li>
                        <li>All contents of the Platform are proprietary and licensed to the Platform Owner.</li>
                        <li>Unauthorized use may lead to legal action.</li>
                        <li>You agree to pay charges associated with availing the Services.</li>
                        <li>You agree not to use the Platform for unlawful or prohibited purposes.</li>
                    </ul>
                </div>
            </section>

            <section>
                <h2 className="text-xl font-bold text-gray-900 mb-4">Third-Party Links</h2>
                <p className="text-gray-600 leading-relaxed">
                    The Platform may contain links to third-party websites governed by their own policies.
                </p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-gray-900 mb-4">Transactions</h2>
                <p className="text-gray-600 leading-relaxed">
                    Upon initiating a transaction, you enter into a legally binding contract with the Platform Owner.
                </p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-gray-900 mb-4">Indemnification</h2>
                <p className="text-gray-600 leading-relaxed">
                    You shall indemnify and hold harmless the Platform Owner against any claims arising out of breach of Terms.
                </p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-gray-900 mb-4">Force Majeure</h2>
                <p className="text-gray-600 leading-relaxed">
                    Force majeure events exempt liability for non-performance.
                </p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-gray-900 mb-4">Governing Law & Jurisdiction</h2>
                <p className="text-gray-600 leading-relaxed mb-4">
                    These Terms shall be governed by the laws of India.
                </p>
                <p className="text-gray-600 leading-relaxed">
                    All disputes shall be subject to the exclusive jurisdiction of Indian courts.
                </p>
            </section>

            <section>
                <h2 className="text-xl font-bold text-gray-900 mb-4">Contact</h2>
                <p className="text-gray-600 leading-relaxed">
                    All communications must be made using contact information provided on the website.
                </p>
            </section>
        </article>
    );
}

export default function TermsAndConditions() {
    return (
        <div className="min-h-screen bg-white text-gray-900">
            {/* Minimal Header */}
            <header className="border-b border-gray-200 bg-white sticky top-0 z-10">
                <div className="container mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
                    <Link to="/" className="flex items-center gap-2 text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors">
                        <ArrowLeft className="h-4 w-4" />
                        Back to Home
                    </Link>
                    <span className="text-sm text-gray-400">Zivah Medical Hub</span>
                </div>
            </header>

            <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-12 lg:py-20">
                <div className="max-w-3xl mx-auto">
                    {/* Document Title */}
                    <div className="mb-12 border-b border-gray-200 pb-8">
                        <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4 tracking-tight">Terms and Conditions</h1>
                        <p className="text-gray-500 text-sm">Last updated: January 2026</p>
                    </div>

                    {/* Content */}
                    <TermsContent />

                    {/* Contact Footer */}
                    <div className="pt-12 border-t border-gray-200 mt-12">
                        <p className="text-gray-600 text-sm">
                            If you have any questions regarding these terms, please contact us at <a href="mailto:legal@zivahmedicalhub.com" className="text-blue-600 hover:underline">legal@zivahmedicalhub.com</a>.
                        </p>
                    </div>
                </div>
            </main>
        </div>
    );
}
